OPSEXP-1257 make sure alpine base is updated
Alfresco/alfresco-docker-base-java pull request #83
Opened 2022-02-18 09:38 UTC by gionn

OPSEXP-1257

2022-02-18 09:46 UTC, mteodori requested changes
please replace with 3.15.0 without sha256 that seems incorrect, semver is enough, no need to update packages

2022-02-18 10:07 UTC, mteodori commented
> * in addition to that, if you set `3.15.0` you are not getting any bugfix update unless **manually** updating to `3.15.1` when it became available.

this is fine, dependabot can create the PR when there is semver

2022-02-18 12:10 UTC, mteodori approved these changes
minor change

2022-02-18 12:10 UTC, mteodori commented on Dockerfile
> +RUN apk update && \
we can use the short form `apk -U upgrade` and add `--no-cache` to all commands or add `rm -vrf /var/cache/apk/*` after to save a few MB of package index - see: https://newbedev.com/alpine-dockerfile-advantages-of-no-cache-vs-rm-var-cache-apk

2022-02-21 08:17 UTC, alxgomz approved these changes
LGTM

2022-02-21 08:21 UTC, merged